version: '3.8'

services:
  trading-dashboard:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - APCA_API_BASE_URL=${APCA_API_BASE_URL}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: trading-network