services:
  # Unified Trading Dashboard Web Service
  - type: web
    name: trading-dashboard
    env: node
    buildCommand: npm install && pip3 install -r requirements.txt
    startCommand: node scripts/init_db.js && npm run render:start
    plan: starter
    envVars:
      # Market Data API
      - key: POLYGON_API_KEY
        sync: false
      
      # Alpaca Trading API (Paper Trading)  
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
        
      # Legacy variable names (for compatibility)
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY  
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SERVE_STATIC
        value: true
        
      # Unified Engine Configuration
      - key: USE_UNIFIED_ENGINE
        value: "1"
      - key: NEW_DASH_ENABLED
        value: "true"
      - key: PORTFOLIO_INTELLIGENCE
        value: "true"
      - key: SELECT_ENGINE
        value: optimized
      - key: ORDERS_ENABLED
        value: "1"
        
      # Same-origin URL configuration (empty = relative URLs)
      - key: NEXT_PUBLIC_DISCOVERY_URL
        value: ""
      - key: NEXT_PUBLIC_PORTFOLIO_URL
        value: ""
      - key: NEXT_PUBLIC_ALPACA_PROXY_URL
        value: ""
        
      # Admin Authentication
      - key: ADMIN_TOKEN
        sync: false
        
      # Trading Configuration
      - key: VIGL_BUY_THRESH
        value: 70
      - key: VIGL_WATCH_THRESH
        value: 55
      - key: VIGL_MONITOR_THRESH
        value: 35
      - key: SCAN_MAX_TICKERS
        value: 1200
        
      # Risk Management (Conservative Go-Live)
      - key: MAX_DAILY_NOTIONAL
        value: "500"
      - key: MAX_TICKER_EXPOSURE
        value: "150"
        
      # Scoring Configuration (keep as single line JSON)
      - key: SCORING_WEIGHTS_JSON
        value: '{"short_interest_weight":2.0,"borrow_fee_weight":1.5,"volume_weight":1.2,"momentum_weight":1.0,"catalyst_weight":0.8,"float_penalty_weight":-0.6}'
    
    # Health check configuration
    healthCheckPath: /api/health
    
    # Auto-deploy from main branch
    autoDeploy: true