# Render deployment configuration
# Copy this configuration to Render dashboard or use for reference

services:
  - type: web
    name: trading-dashboard-web
    env: node
    region: oregon  # or your preferred region
    plan: starter  # or higher
    buildCommand: node scripts/write_build_stamp.js && npm ci
    startCommand: npm run render:start
    envVars:
      - key: SERVICE_ROLE
        value: web
      - key: NODE_ENV
        value: production
      - key: STRICT_STARTUP
        value: false
      - key: SCREENER_STRICT_FEEDS
        value: false
    
  - type: worker
    name: trading-dashboard-worker  
    env: node
    region: oregon
    plan: starter
    buildCommand: node scripts/write_build_stamp.js && npm ci
    startCommand: ROLE=worker npm run render:start
    envVars:
      - key: SERVICE_ROLE
        value: worker
      - key: ROLE
        value: worker
      - key: NODE_ENV
        value: production
      - key: STRICT_STARTUP
        value: false
      - key: SCREENER_STRICT_FEEDS
        value: false
      - key: OUTCOME_LABELER_ENABLED
        value: true

# Environment variables to set in Render dashboard:
# 
# Required for both services:
# - POLYGON_API_KEY: Your Polygon.io API key
# - APCA_API_KEY_ID: Alpaca paper trading API key ID  
# - APCA_API_SECRET_KEY: Alpaca paper trading secret key
# - ALPACA_TRADING_BASE: https://paper-api.alpaca.markets
# - ALPACA_DATA_BASE: https://data.alpaca.markets
#
# Optional:
# - ADMIN_TOKEN: For protected admin endpoints (defaults to "test123")
# - SQLITE_DB_PATH: Custom database path (defaults to ./trading_dashboard.db)