services:
  # Background VIGL Scanner Worker
  - type: worker
    name: vigl-scanner-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python vigl_background_worker.py
    envVars:
      - key: POLYGON_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: vigl-database
          property: connectionString
    
  # Web API Service
  - type: web
    name: vigl-api-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn vigl_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vigl-database
          property: connectionString
    
  # Frontend Web Service
  - type: web
    name: vigl-frontend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: VIGL_API_URL
        value: https://vigl-api-service.onrender.com
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false

# Database
databases:
  - name: vigl-database
    databaseName: vigl_db
    user: vigl_user